# Generated by Django 4.0.6 on 2022-07-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticitem',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
