# Generated by Django 4.0.6 on 2022-07-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_api', '0002_alter_elasticitem_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticitem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
